<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DomainServices\**" />
    <EmbeddedResource Remove="DomainServices\**" />
    <None Remove="DomainServices\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\DomainFundamentals\DomainFundamentals.csproj" />
    <ProjectReference Include="..\Folders\Folders.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="UseCases\CreateRoot\CreateRootCommand.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.0.0" />
  </ItemGroup>

</Project>
