// <auto-generated />
using System;
using Folders.Infrastructure.Persistence.DatabaseContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Folders.Infrastructure.Migrations
{
    [DbContext(typeof(FoldersDbContext))]
    partial class FoldersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Folders.Core.Aggregates.FolderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentFolderId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentFolderId");

                    b.ToTable("FolderItems", (string)null);

                    b.HasDiscriminator<string>("FolderItemType").HasValue("FolderItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Folders.Core.Aggregates.File", b =>
                {
                    b.HasBaseType("Folders.Core.Aggregates.FolderItem");

                    b.HasDiscriminator().HasValue("File");
                });

            modelBuilder.Entity("Folders.Core.Aggregates.Folder", b =>
                {
                    b.HasBaseType("Folders.Core.Aggregates.FolderItem");

                    b.HasDiscriminator().HasValue("Folder");
                });

            modelBuilder.Entity("Folders.Core.Aggregates.FolderItem", b =>
                {
                    b.HasOne("Folders.Core.Aggregates.Folder", "ParentFolder")
                        .WithMany("Items")
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("Folders.Core.Aggregates.File", b =>
                {
                    b.OwnsOne("Folders.Core.Values.StorageInfo", "StorageInfo", b1 =>
                        {
                            b1.Property<Guid>("FileId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("MimeType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("MimeType");

                            b1.Property<long>("Size")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Size");

                            b1.Property<string>("StorageId")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)")
                                .HasColumnName("StorageId");

                            b1.HasKey("FileId");

                            b1.ToTable("FolderItems");

                            b1.WithOwner()
                                .HasForeignKey("FileId");
                        });

                    b.Navigation("StorageInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Folders.Core.Aggregates.Folder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
